version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_backend
    restart: unless-stopped
    command: >
      uvicorn app:app --host 0.0.0.0 --port 8000 --workers 4
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./:/backend

volumes:
  postgres_data:
